config/routes.rb
ExamsSystem::Application.routes.draw do
  resources :news_feeds

  mount Ckeditor::Engine => '/ckeditor'

  get "/topic_linkings/fetch_topic_linkings" => "topic_linkings#fetch_topic_linkings"

  resources :topic_linkings do
    collection do
      post :get_course_link
      get :get_topic_course_link
    end
  end

  resources :course_linkings
  resources :news_feeds
  resources :ckeditor, controller: 'ckeditor/'

  resources :membership_plans

  get "/questions/fetch_courses" => "questions#fetch_courses"
  get "/questions/fetch_details" => "questions#fetch_details"
  get "/questions/fetch_ques" => "questions#fetch_ques"
  get "/questions/fetch_course" => "questions#fetch_course"
  get "workflow_paths/fetch_reviews" => "workflow_paths#fetch_reviews"
  get "/topics/fetch_courses" => "topics#fetch_courses"
  get "/topics/fetch_table" => "topics#fetch_table"

  get "workflow_paths" => "workflow_paths#index"
  get "workflow_paths/toggle_workflow" => "workflow_paths#toggle_workflow"
  get "user" => "teacher#index"

  get 'auth/:provider/callback' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get "user/new" => "teacher#new"
  post "user/save_result"
  get "user/my_profile"
  get "user/progress"
  put 'user/update_password'
  post "user/request_teacher"
  get "user/get_courses_by_degree_id"
  get "user/dashboard"
  get "user/ReTakeTest"
  get "user/manage_courses" => "user#manage_courses"
  get "/teachers/fetch_users" => "teacher#fetch_users"

  put "/user/update_courses" => "user#update_courses"

  delete "user.:id" => "teacher#destroy"

  get "home_page/user/my_profile" => "user#my_profile"
  get "home_page/checkout_form" => "home_page#checkout_form"
  get "/home_page/receipt" => "home_page#receipt"

  put "user/update"
  get "/courses/get_courses_by_degree_id"

  get "/boards/manage_boards" => "boards#manage_boards"
  get "/degrees/manage_degrees" => "degrees#manage_degrees"

  get "/course_linkings/manage_course_linkings" => "course_linkings#manage_course_linkings"
  get "/courses/manage_courses" => "courses#manage_courses"

  get "/courses/fetch_courses" => "courses#fetch_courses"
  get "/quizzes/fetch_courses" => "quizzes#fetch_courses"
  get "/quizzes/fetch_quizzes" => "quizzes#fetch_quizzes"

  get "/topics/fetch_topics" => 'topics#fetch_topics'

  resources :boards

  resources :topics do
    collection do
      get :get_courses
      get :get_topics
    end
  end

  resources :teacher do
    collection do
      get :get_courses
      get :teacher_courses
      post :course_register
      get :accept_student
      get :reject_student

    end

  end

  resources :books do
    collection do
      get :get_courses
    end
  end

  resources :services, except: [:show] do
    collection do
      post :sign_in
      get :get_all_boards
      get :get_all_degrees
      get :is_questions_exists
      get :fetch_questions
      get :get_lookup_data
      get :is_test_exists
      get :get_questions_by_test_code
      get :get_options_by_question_id
      get :verify_answers
      get :get_courses_by_teacher
      get :get_questions
      get :get_els_questions
      get :quiz
      post :create_quiz
      get :get_quiz_list
      get :get_student_quiz_list
      get :get_live_score_list
      get :live_score_details
      get :get_topics
      get :verify_answers_web
      get :show_quiz
      post :upload_image
      get :fetch_teacher_list
      get :fetch_quizzes
      get :fetch_answers
      post :save_remarks
      post :upload_video
      post :comment_feedback
      get :reviewed_quiz
      get :submit_feedback
      get :finish_review
      get :quizzes_list
      get :get_test_history_details
    end
  end

  resources :questions do
    collection do
      get :get_courses
      get :get_ques
      get :add_questions
      get :get_tests
      get :render_view
      get :render_view_edit
      get :delete_ques
      get :get_limit
      get :demo
      get :questions_approval
      get :approve_question
      get :next_question
      get :previous_question
      post :approve_by_teacher
      post :past_paper_history_param
      get :past_paper_history_param_edit
      post :reject_by_teacher
      get :reject_question
      post :reject_question
      get :add_comment_to_question
      get :get_questions_by_status
      get :get_question_details_for_approval
      get :questions_exits
      put :update_topic
      get :remove_option
      get :questions_detail
      get :get_question_detail
      get :enable_question_review
      get :get_course_linking
      get :get_topic_course_link
      get :get_all_topics_from_topic_linking
      get :rejected_questions
    end
  end

  get "home_page/index"
  get "home_page/get_courses" => 'home_page#get_courses'
  get "home_page/get_degrees" => 'home_page#get_degrees'
  get "home_page/get_tests" => 'home_page#get_tests'
  get "home_page/instructions" => 'home_page#instructions'
  post "home_page/instructions" => 'home_page#instructions'
  post "home_page/quiz" => 'home_page#quiz'
  get "home_page/quiz" => 'home_page#quiz'
  get "home_page/next_ques" => 'home_page#next'
  get "home_page/user_graph" => 'home_page#user_graph'
  get "home_page/get_notes_courses" => 'home_page#notes_courses'
  get "home_page/get_notes" => 'home_page#get_notes'
  get "home_page/create_user_registration" => "home_page#create_user_registration"
  post "home_page/sign_in_user" => "home_page#sign_in_user"
  get "home_page/add_user_test" =>  "home_page#add_user_test"
  get "home_page/is_user_signed_in" => "home_page#is_user_signed_in"
  get "home_page/demo" => "home_page#demo"
  get "admin_panel" => "home_page#admin_panel"
  get "home_page/save_data" => 'home_page#save_data'
  get "home_page/save_answer" => 'home_page#save_answer_to_session'
  get "home_page/get_answer" => 'home_page#get_answer_from_session'
  get "aboutUs" => 'home_page#about_us'
  get "pricing" => 'home_page#pricing'
  get "try_it" => 'home_page#try_it'
  post "home_page/get_topic" => 'home_page#get_topic'
  get "how_it_works" => 'home_page#how_it_works'
  get "testimonials" => 'home_page#testimonials'
  get "home_page/assign_member_ship_plan" => "home_page#assign_member_ship_plan"
  post "home_page/checkout" => "home_page#checkout"

  get "home_page/get_varients"
  get "home_page/get_backup"
  get "home_page/payments" => "home_page#payments"
  post "/homepage/set_access" => "home_page#set_access"
  get "/home_page/questions/questions_detail" => "questions#questions_detail"
  post "/home_page/get_details" => "home_page#get_details"
  get "/homepage/check_student_package" => "home_page#check_student_package"
  post "/homepage/check_package" => "home_page#check_package"
  get "/home_page/fetch_teachers" => "home_page#fetch_teachers"

  resources :tests do
    collection do
      get :get_courses
      get :get_questions
    end
  end
  resources :quizzes do
    collection do
      get :get_courses
      get :get_questions
      get :get_els_questions
      get :test_exists
      get :get_questions_by_course
      get :get_topics
      get :get_next_question
    end
  end

  get "/home_page/get_session", :to => 'home_page#get_session'

  resources :courses

  resources :degrees

  resources :roles

  root :to => "home_page#index"

  delete "/user/delete_package", to: "user#delete_package"

  get "/user/add_course", to: "user#add_course"

  get "/user/fetch_packages", to: "user#fetch_packages"

  get "/user/buy", to: "user#buy"

  get "/user/purchase", to: "user#purchase"

  devise_for :users, :controllers=> {:sessions=> "users/sessions",
                                   :confirmations => "users/confirmations",
                                   :passwords => "users/passwords",
                                   :unlocks => "users/unlocks",
                                   :registrations => "users/registrations",
                                   :omniauth_callbacks => "users/omniauth_callbacks"

  }

  devise_scope :user do
    get "sign_up" => "users/registrations#new"
    get "sign_in" => "users/sessions#new"
    delete "sign_out" => "users/sessions#destroy"
    put "users/save_form_2" => "users/registrations#save_form_2"
    get "/user_exists" => "users/registrations#user_exists"
    post "/save_form_1" => "users/registrations#save_form_1"
    post "/save_form_2" => "users/registrations#save_form_2"
    post "/save_form_3" => "users/registrations#save_form_3"
    post "/registration" => "users/registrations#registration"
    get "/registration" => "users/registrations#registration"
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  get "/student/fetch_image" => "teacher#fetch_image"
  post "/student/upload_video" => "teacher#upload_video"
  get "/student_test" => "teacher#student_test"

  post "/save_remarks" => "teacher#save_remarks"
  get "/user/test_reviews" => "user#test_reviews"
  get "/user/quiz_answers" => "user#quiz_answers"
  get "/student/show_answer" => "user#show_answer"

  get "new_students" => "teacher#new_students"
  get "manage_students" => "teacher#manage_students"
  get "/check_quiz" => "teacher#check_quiz"

  get "/student/review_question" => "teacher#review_question"
  post "/student/submit_feedback" => "user#submit_feedback"
  get "/comment_feedback" => "teacher#comment_feedback"
  get "/get_teachers" => "home_page#get_teachers"
  post "/teachers/finish_review" => "teacher#finish_review"
  post "/home_page/upload_image" => "home_page#upload_image"
  post "/student/upload_image" => "teacher#upload_image"
  get "/teachers/reviewed_quizzes" => "teacher#reviewed_quizzes"
  get "/teachers/video_reviewed_quizzes" => "teacher#video_reviewed_quizzes"
  get "/teachers/preview_reviewed_quiz" => "teacher#preview_reviewed_quiz"
  get "/teachers/preview_question" => "teacher#preview_question"
  get "/teachers/next_image" => "teacher#next_image"
  get "/home_page/remove_image" => "home_page#remove_image"

end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/teacher/_courselist.html.erb
<%=label_tag :course %>

<% if @courses.nil? %>
<% else %>

    <select id="course" name="course" >

      <%@courses.each do |x| %>

          <option value="<%=x.id%>"><%=x.name%></option>
      <% end %>
    </select>

<%end %>

app/views/teacher/_edit_image.html.erb
<br><br><font size="6"><span id="current_image"><%= ((imagees.size - imagee_ids.size) + 1) %></span>/<span id="total_images"><%= imagees.size %></span></font><br>
<iframe src="https://www.picozu.com/editor/?i=<%= imagee.image.url.gsub("http", "https").split("?")[0] %>&workspace=0&theme=galaxy&key=Ci8Mh5lIdX1Me3kB" width="900" height="600"></iframe>
<%= hidden_field_tag :image_id, imagee.id %>

<script>

  $(document).ready(function() {
//    var h =  $('iframe').contents().find('.accept-button')
//    console.dir(h)
//    $('iframe').contents().find('.accept-button').click(function()
//    {
//      alert("Functionality defined by def");
//    });

//    save_image();

  });
</script>

app/views/teacher/_fetch_users.html.erb
<table class="table table-condensed">
  <thead>
  <th>Emails</th>
  <th>Name</th>
  <th>Contact number</th>
  <th>Role</th>
  <th>Action</th>
  </thead>
  <tbody>
  <%@users.each do |user|  %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.roles.first.name unless user.roles.first.nil? %></td>
        <td><%= link_to 'Edit', edit_teacher_path(user) %>/
          <%= link_to 'Delete', user, :method=> :delete, :data=> { :confirm=> 'Are you sure?' } %></td>



      </tr>



  <% end %>
  </tbody>


</table>

<script type="text/javascript">
  $(document).ready(function() {
    $('.table').dataTable();
  } );


</script>

app/views/teacher/_reviewed_quizzes.html.erb
<div class="listing-holder">
  <table class="table table-condensed">
    <thead>
    <tr>
      <th>Name</th>
      <th>Course</th>
      <th>Test Code</th>
      <th>No. of Questions</th>
      <th>Date</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @reviewed_tests.each do |test| %>
        <tr>
          <td><%= test.quiz_name %></td>
          <td><%= @reviewed_test_courses.select{|course| test.course_id == course.id}.first.name %></td>
          <td><%= test.code %></td>
          <td><%= test.descriptive.split(',').count %></td>
          <td><%= test.created_at.to_date %></td>
          <td><%= link_to "Review", teachers_preview_reviewed_quiz_path(test_id: test.id) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/teacher/_video_reviewed_quizzes.html.erb
<div class="listing-holder">
  <table class="table table-condensed">
    <thead>
    <tr>
      <!--<th>Student name</th>-->
      <th>Name</th>
      <th>Course</th>
      <th>Test Code</th>
      <th>No. of Questions</th>
      <th>Date</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @reviewed_tests.each do |test| %>
        <tr>
          <!--<td><%#= @students.select{|student| test.user_id == student.id}.first.name if @students.select{|student| test.user_id == student.id}.first %></td>-->
          <td><%= test.quiz_name %></td>
          <td><%= @reviewed_test_courses.select{|course| test.course_id == course.id}.first.name %></td>
          <td><%= test.code %></td>
          <td><%= test.descriptive.split(',').count %></td>
          <td><%= test.created_at.to_date %></td>
          <td><%= link_to "Review", teachers_preview_reviewed_quiz_path(test_id: test.id) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/teacher/accept_student.js.erb
alert("<%= @message %>");
<% if @flag == true %>
    $("<%=@row_id%>").hide();
<% end %>

app/views/teacher/check_quiz.html.erb
<% if current_user.is_admin? %>
    <div class="wrapper page-heading border-bottom white-bg">
      <%= link_to "Manage Tests", quizzes_path, class: "btn btn-inverse" %>
      <%= link_to "Comment Feedback", "/comment_feedback", class: "btn btn-inverse" %>
      <%= link_to "Video Feedback", "/check_quiz", class: "btn btn-inverse" %>
    </div>

<% elsif current_user.is_teacher? %>
    <div class="wrapper page-heading border-bottom white-bg">
    <%= link_to "Video Feedback", "#", id: "video_feedback", class: "btn btn-inverse" %>
    <%= link_to "Reviewed", "#", id: "reviewed_quizzes", class: "btn btn-inverse" %>
    </div>
<% end %>
<div class="wrapper wrapper-content">
  <div class="ibox">
    <div class="ibox-title">
      <h5>Student's Quizzes</h5>
    </div>
    <div class="ibox-content">
      <div id="check">
        <div class="listing-holder">
          <table class="table table-condensed">
            <thead>
            <tr>
              <!--<th>Student name</th>-->
              <th>Name</th>
              <th>Course</th>
              <th>Test Code</th>
              <th>No. of Questions</th>
              <th>Date</th>
              <th>Status</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @tests.each do |test| %>
                <tr>
                  <!--<td><%#= @students.select{|student| test.user_id == student.id}.first.name if @students.select{|student| test.user_id == student.id}.first %></td>-->
                  <td><%= test.quiz_name %></td>
                  <td><%= @courses.select{|course| test.course_id == course.id}.first.name %></td>
                  <td><%= test.code %></td>
                  <td><%= test.descriptive.nil? ? "":test.descriptive.split(',').count %></td>
                  <td><%= test.created_at.to_date %></td>
                  <td><%= test.answers.where(:reviewed => true).count %></td>
                  <td><%= link_to "Review Test", "/student_test?test_id=#{test.id}" %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>





<script>
  $('#video_feedback').on('click', function(){
    $('#check').show();
    $('#reviewed').hide();
  })

  $('#reviewed_quizzes').on('click', function(){
    $('#check').hide();
    $('#reviewed').show();
  })
</script>

app/views/teacher/comment_feedback.html.erb
<% if current_user.is_admin? %>
<div class="wrapper page-heading white-bg border-bottom">
    <%= link_to "Manage Tests", quizzes_path, class: "btn btn-inverse" %>
    <%= link_to "Comment Feedback", "/comment_feedback", class: "btn btn-inverse" %>
    <%= link_to "Video Feedback", "/check_quiz", class: "btn btn-inverse" %>
</div>
<% elsif current_user.is_teacher? %>
    <div class="wrapper page-heading white-bg border-bottom">
    <%= link_to "Comment Feedback", "#", id: "comment_feedback", class: "btn btn-inverse" %>
    <%= link_to "Reviewed", "#", id: "reviewed_quizzes", class: "btn btn-inverse" %>
    </div>
<% end %>

<div class="wrapper wrapper-content">
  <div class="ibox">
    <div class="ibox-title">
      <h5>Student's Quizzes</h5>
    </div>
    <div class="ibox-content">
      <div id="check">
        <div class="listing-holder">
          <table class="table table-condensed">
            <thead>
            <tr>
              <th>Name</th>
              <th>Course</th>
              <th>Test Code</th>
              <th>No. of Questions</th>
              <th>Date</th>
              <th>Status</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @tests.each do |test| %>
                <tr>
                  <td><%= test.quiz_name %></td>
                  <td><%= @courses.select{|course| test.course_id == course.id}.first.name %></td>
                  <td><%= test.code %></td>
                  <td><%= test.descriptive.nil? ? "":test.descriptive.split(',').count %></td>
                  <td><%= test.created_at.to_date %></td>
                  <td><%= test.answers.where(:reviewed => true).count %></td>
                  <td><%= link_to "Review Test", "/student_test?test_id=#{test.id}" %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>





<script>
  $('#comment_feedback').on('click', function(){
    $('#check').show();
    $('#reviewed').hide();
  })

  $('#reviewed_quizzes').on('click', function(){
    $('#check').hide();
    $('#reviewed').show();
  })
</script>

app/views/teacher/manage_students.html.erb
<!--<h1>New Students</h1>-->

<!--<div class="listing-holder">-->
  <!--<table class="table table-condensed">-->
    <!--<thead>-->
    <!--<tr>-->
      <!--<th>Name</th>-->
      <!--<th>Email</th>-->
      <!--<th>Reject</th>-->

    <!--</tr>-->
    <!--</thead>-->
    <!--<tbody>-->
    <!--<% @students.each do |student| %>-->
        <!--<tr id="row_<%= student.id %>">-->
          <!--<td><%= student.student_name %></td>-->
          <!--<td><%= student.student_email %></td>-->
          <!--<td><%= link_to "Remove","teacher/reject_student?id=#{student.id}",remote: true %></td>-->
        <!--</tr>-->
    <!--<% end %>-->
    <!--</tbody>-->
  <!--</table>-->
<!--</div>-->

<!--<% if can? :manage, Board %>-->
    <!--<%= link_to 'New Board', new_board_path, :class=> 'btn btn-large btn-inverse' %>-->
<!--<% end %>-->


<div class="row wrapper page-heading border-bottom white-bg">
  <h1>Manage Students</h1>
</div>

<div class="row wrapper wrapper-content">
  <div class="ibox float-e-margin">
    <div class="ibox-title">
      <h5>Students</h5>
    </div>
    <div class="ibox-content listing-holder">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Reject</th>

        </tr>
        </thead>
        <tbody>
        <% @students.each do |student| %>
            <tr id="row_<%= student.id %>">
              <td><%= student.student_name %></td>
              <td><%= student.student_email %></td>
              <td><%= link_to "Reject","teacher/reject_student?id=#{student.id}",remote: true %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row wrapper ">
  <% if can? :manage, Board %>
      <%= link_to 'New Board', new_board_path, :class=> 'btn btn-large btn-inverse' %>
  <% end %>
</div>

app/views/teacher/preview_question.html.erb
<div class="page-content-wrapper">
  <div class=" stat_holder" style="margin-top: 20px">
    <label><strong>Question Statement</strong></label>
    <%= raw @question.statement %>
  </div>

  <div class="field stat_holder">

    <% unless @answer.answer_detail %>
        <label><strong>Teacher Review</strong></label>
        <%= image_tag @answer.image.url %>
    <% else %>
        <label><strong>Submitted Answer</strong></label>
        <%= raw @answer.answer_detail %>
    <% end %>
  </div>

  <div class="field stat_holder">
    <label><strong>Remarks</strong></label>
    <%= @answer.remarks %>
  </div>

  <div class="field stat_holder">
    <label><strong>Marks</strong></label>
    <%= @answer.marks %> / <%= @question.marks %>
  </div>

  <% if @answer.video_file_name %>
      <div class="field stat_holder">
        <label><strong>Video Review</strong></label>
        <div  style="width:800px; margin:0 auto;">
          <video id="example_video_1" class="video-js vjs-default-skin vjs-big-play-centered"
                 controls preload="auto" width="640" height="400"
                 poster="http://video-js.zencoder.com/oceans-clip.png"
                 data-setup='{"example_option":true}'>
            <source src="<%= @answer.video %>" type="video/webm" />
            <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
          </video>
        </div>

      </div>
  <% end %>

  <% if @answer.video_file_name %>
      <% if @finish_flag %>
          <%= link_to "Finish Review", check_quiz_path, class: "btn btn-primary" %>
      <% else %>
          <%= link_to "Next Answer", teachers_preview_question_path, class: "btn btn-primary" %>
      <% end %>
  <% else %>
      <% if @finish_flag %>
          <%= link_to "Finish Review", comment_feedback_path, class: "btn btn-primary" %>
      <% else %>
          <%= link_to "Next Answer", teachers_preview_question_path, class: "btn btn-primary" %>
      <% end %>
  <% end %>

</div>

app/views/teacher/reject_student.js.erb
alert("<%= @message %>");
<% if @flag == true %>
    $("<%=@row_id%>").hide();
<% end %>

app/views/teacher/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email Address:</b>
  <%= @user.email %>
</p>

<p>
  <b>Phone Number:</b>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_teacher_path(@user) %> |
<%= link_to 'Back', teacher_index_path %>

app/views/teacher/teacher_courses.html.erb
<div class="row">
  <div class="span6">
    <%= form_for :user, :url => {:controller => 'teacher', :action => 'course_register'} do |f| %>

        <% Board.all.each do |board| %>
            <%if @boards.find {|x| x.id == board.id} %>
                <%= check_box_tag 'boards[]', board.id,true, :class => 'checkboxes' %><%=board.name %>
            <%else %>
                <%= check_box_tag 'boards[]', board.id,false %><%=board.name %>
            <%end %>

        <% end %>

        <div class="field">
          <%=f.label :degree %>
          <select id="degree" name="degree" onchange="generate_courses(this)">
            <option>Select Degree</option>
            <% Degree.all.each do |degree| %>


                <option value="<%=degree.id%>"><%=degree.name%></option>

            <% end %>
          </select>
        </div>






        <div id="course_container" class="field">
          <%=label_tag :course %>
          <select id="course" name="course" >
            <option>Select Degree First</option>
          </select>
        </div>

        <%=f.hidden_field :user_id, value: @user.id  unless @user.id.nil? %>
        <%=f.submit :register, class: 'btn btn-inverse' %>
        <%=link_to :done, home_page_index_path, :class => 'btn btn-inverse' %>
    <% end %>


  </div>
  <div class="span4">
    <table class="table table-condensed">
      <th>Teacher</th>
      <th>Degree</th>
      <th>Course</th>
      <%@user.teacher_courses.all.each do |t_course| %>
      <tr>

        <td><%= @user.name %></td>
        <td><%=DegreeCourseAssignment.find_by_id(t_course).degree.name %></td>
        <td><%=DegreeCourseAssignment.find_by_id(t_course).course.name %></td>
      </tr>
      <%end %>
    </table>

  </div>
</div>



<script>
    $(document).ready(function() {
                //$('#course_container').hide();
            }
    );

    function generate_courses(degree_id)
    {
        //alert (degree_id.value);
        container = document.getElementById('course_container');
        $.ajax({
            url:'/teacher/get_courses?degree_id='+degree_id.value,
            type:'get',
            dataType:'html',
            processData:false,
            success:function (data) {
                $("#course_container").html(data);
                $("#course_container").show();
            },
            error:function (data) {
                alert ('nae chalaa');
                //    window.location.reload();
            }
        });

    }

</script>

app/views/teacher/video_reviewed_quizzes.html.erb
<% if current_user.is_admin? %>
    <%= link_to "Manage Tests", quizzes_path, class: "btn btn-primary" %> |
    <%= link_to "Comment Feedback", "/comment_feedback", class: "btn btn-primary" %> |
    <%= link_to "Video Feedback", "/check_quiz", class: "btn btn-primary" %>
<% elsif current_user.is_teacher? %>
    <%= link_to "Video Feedback", "/check_quiz", class: "btn btn-primary" %> |
    <%= link_to "Reviewed Quizzes", "/teachers/video_reviewed_quizzes", class: "btn btn-primary" %>
<% end %>

<h1>Student's Quizzes</h1>

<div class="listing-holder">
  <table class="table table-condensed">
    <thead>
    <tr>
      <!--<th>Student name</th>-->
      <th>Name</th>
      <th>Course</th>
      <th>Test Code</th>
      <th>No. of Questions</th>
      <th>Date</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @tests.each do |test| %>
        <tr>
          <!--<td><%#= @students.select{|student| test.user_id == student.id}.first.name if @students.select{|student| test.user_id == student.id}.first %></td>-->
          <td><%= test.quiz_name %></td>
          <td><%= @courses.select{|course| test.course_id == course.id}.first.name %></td>
          <td><%= test.code %></td>
          <td><%= test.descriptive.split(',').count %></td>
          <td><%= test.created_at.to_date %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>