config/routes.rb
ExamsSystem::Application.routes.draw do
  resources :news_feeds

  mount Ckeditor::Engine => '/ckeditor'

  get "/topic_linkings/fetch_topic_linkings" => "topic_linkings#fetch_topic_linkings"

  resources :topic_linkings do
    collection do
      post :get_course_link
      get :get_topic_course_link
    end
  end

  resources :course_linkings
  resources :news_feeds
  resources :ckeditor, controller: 'ckeditor/'

  resources :membership_plans

  get "/questions/fetch_courses" => "questions#fetch_courses"
  get "/questions/fetch_details" => "questions#fetch_details"
  get "/questions/fetch_ques" => "questions#fetch_ques"
  get "/questions/fetch_course" => "questions#fetch_course"
  get "workflow_paths/fetch_reviews" => "workflow_paths#fetch_reviews"
  get "/topics/fetch_courses" => "topics#fetch_courses"
  get "/topics/fetch_table" => "topics#fetch_table"

  get "workflow_paths" => "workflow_paths#index"
  get "workflow_paths/toggle_workflow" => "workflow_paths#toggle_workflow"
  get "user" => "teacher#index"

  get 'auth/:provider/callback' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get "user/new" => "teacher#new"
  post "user/save_result"
  get "user/my_profile"
  get "user/progress"
  put 'user/update_password'
  post "user/request_teacher"
  get "user/get_courses_by_degree_id"
  get "user/dashboard"
  get "user/ReTakeTest"
  get "user/manage_courses" => "user#manage_courses"
  get "/teachers/fetch_users" => "teacher#fetch_users"

  put "/user/update_courses" => "user#update_courses"

  delete "user.:id" => "teacher#destroy"

  get "home_page/user/my_profile" => "user#my_profile"
  get "home_page/checkout_form" => "home_page#checkout_form"
  get "/home_page/receipt" => "home_page#receipt"

  put "user/update"
  get "/courses/get_courses_by_degree_id"

  get "/boards/manage_boards" => "boards#manage_boards"
  get "/degrees/manage_degrees" => "degrees#manage_degrees"

  get "/course_linkings/manage_course_linkings" => "course_linkings#manage_course_linkings"
  get "/courses/manage_courses" => "courses#manage_courses"

  get "/courses/fetch_courses" => "courses#fetch_courses"
  get "/quizzes/fetch_courses" => "quizzes#fetch_courses"
  get "/quizzes/fetch_quizzes" => "quizzes#fetch_quizzes"

  get "/topics/fetch_topics" => 'topics#fetch_topics'

  resources :boards

  resources :topics do
    collection do
      get :get_courses
      get :get_topics
    end
  end

  resources :teacher do
    collection do
      get :get_courses
      get :teacher_courses
      post :course_register
      get :accept_student
      get :reject_student

    end

  end

  resources :books do
    collection do
      get :get_courses
    end
  end

  resources :services, except: [:show] do
    collection do
      post :sign_in
      get :get_all_boards
      get :get_all_degrees
      get :is_questions_exists
      get :fetch_questions
      get :get_lookup_data
      get :is_test_exists
      get :get_questions_by_test_code
      get :get_options_by_question_id
      get :verify_answers
      get :get_courses_by_teacher
      get :get_questions
      get :get_els_questions
      get :quiz
      post :create_quiz
      get :get_quiz_list
      get :get_student_quiz_list
      get :get_live_score_list
      get :live_score_details
      get :get_topics
      get :verify_answers_web
      get :show_quiz
      post :upload_image
      get :fetch_teacher_list
      get :fetch_quizzes
      get :fetch_answers
      post :save_remarks
      post :upload_video
      post :comment_feedback
      get :reviewed_quiz
      get :submit_feedback
      get :finish_review
      get :quizzes_list
      get :get_test_history_details
    end
  end

  resources :questions do
    collection do
      get :get_courses
      get :get_ques
      get :add_questions
      get :get_tests
      get :render_view
      get :render_view_edit
      get :delete_ques
      get :get_limit
      get :demo
      get :questions_approval
      get :approve_question
      get :next_question
      get :previous_question
      post :approve_by_teacher
      post :past_paper_history_param
      get :past_paper_history_param_edit
      post :reject_by_teacher
      get :reject_question
      post :reject_question
      get :add_comment_to_question
      get :get_questions_by_status
      get :get_question_details_for_approval
      get :questions_exits
      put :update_topic
      get :remove_option
      get :questions_detail
      get :get_question_detail
      get :enable_question_review
      get :get_course_linking
      get :get_topic_course_link
      get :get_all_topics_from_topic_linking
      get :rejected_questions
    end
  end

  get "home_page/index"
  get "home_page/get_courses" => 'home_page#get_courses'
  get "home_page/get_degrees" => 'home_page#get_degrees'
  get "home_page/get_tests" => 'home_page#get_tests'
  get "home_page/instructions" => 'home_page#instructions'
  post "home_page/instructions" => 'home_page#instructions'
  post "home_page/quiz" => 'home_page#quiz'
  get "home_page/quiz" => 'home_page#quiz'
  get "home_page/next_ques" => 'home_page#next'
  get "home_page/user_graph" => 'home_page#user_graph'
  get "home_page/get_notes_courses" => 'home_page#notes_courses'
  get "home_page/get_notes" => 'home_page#get_notes'
  get "home_page/create_user_registration" => "home_page#create_user_registration"
  post "home_page/sign_in_user" => "home_page#sign_in_user"
  get "home_page/add_user_test" =>  "home_page#add_user_test"
  get "home_page/is_user_signed_in" => "home_page#is_user_signed_in"
  get "home_page/demo" => "home_page#demo"
  get "admin_panel" => "home_page#admin_panel"
  get "home_page/save_data" => 'home_page#save_data'
  get "home_page/save_answer" => 'home_page#save_answer_to_session'
  get "home_page/get_answer" => 'home_page#get_answer_from_session'
  get "aboutUs" => 'home_page#about_us'
  get "pricing" => 'home_page#pricing'
  get "try_it" => 'home_page#try_it'
  post "home_page/get_topic" => 'home_page#get_topic'
  get "how_it_works" => 'home_page#how_it_works'
  get "testimonials" => 'home_page#testimonials'
  get "home_page/assign_member_ship_plan" => "home_page#assign_member_ship_plan"
  post "home_page/checkout" => "home_page#checkout"

  get "home_page/get_varients"
  get "home_page/get_backup"
  get "home_page/payments" => "home_page#payments"
  post "/homepage/set_access" => "home_page#set_access"
  get "/home_page/questions/questions_detail" => "questions#questions_detail"
  post "/home_page/get_details" => "home_page#get_details"
  get "/homepage/check_student_package" => "home_page#check_student_package"
  post "/homepage/check_package" => "home_page#check_package"
  get "/home_page/fetch_teachers" => "home_page#fetch_teachers"

  resources :tests do
    collection do
      get :get_courses
      get :get_questions
    end
  end
  resources :quizzes do
    collection do
      get :get_courses
      get :get_questions
      get :get_els_questions
      get :test_exists
      get :get_questions_by_course
      get :get_topics
      get :get_next_question
    end
  end

  get "/home_page/get_session", :to => 'home_page#get_session'

  resources :courses

  resources :degrees

  resources :roles

  root :to => "home_page#index"

  delete "/user/delete_package", to: "user#delete_package"

  get "/user/add_course", to: "user#add_course"

  get "/user/fetch_packages", to: "user#fetch_packages"

  get "/user/buy", to: "user#buy"

  get "/user/purchase", to: "user#purchase"

  devise_for :users, :controllers=> {:sessions=> "users/sessions",
                                   :confirmations => "users/confirmations",
                                   :passwords => "users/passwords",
                                   :unlocks => "users/unlocks",
                                   :registrations => "users/registrations",
                                   :omniauth_callbacks => "users/omniauth_callbacks"

  }

  devise_scope :user do
    get "sign_up" => "users/registrations#new"
    get "sign_in" => "users/sessions#new"
    delete "sign_out" => "users/sessions#destroy"
    put "users/save_form_2" => "users/registrations#save_form_2"
    get "/user_exists" => "users/registrations#user_exists"
    post "/save_form_1" => "users/registrations#save_form_1"
    post "/save_form_2" => "users/registrations#save_form_2"
    post "/save_form_3" => "users/registrations#save_form_3"
    post "/registration" => "users/registrations#registration"
    get "/registration" => "users/registrations#registration"
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  get "/student/fetch_image" => "teacher#fetch_image"
  post "/student/upload_video" => "teacher#upload_video"
  get "/student_test" => "teacher#student_test"

  post "/save_remarks" => "teacher#save_remarks"
  get "/user/test_reviews" => "user#test_reviews"
  get "/user/quiz_answers" => "user#quiz_answers"
  get "/student/show_answer" => "user#show_answer"

  get "new_students" => "teacher#new_students"
  get "manage_students" => "teacher#manage_students"
  get "/check_quiz" => "teacher#check_quiz"

  get "/student/review_question" => "teacher#review_question"
  post "/student/submit_feedback" => "user#submit_feedback"
  get "/comment_feedback" => "teacher#comment_feedback"
  get "/get_teachers" => "home_page#get_teachers"
  post "/teachers/finish_review" => "teacher#finish_review"
  post "/home_page/upload_image" => "home_page#upload_image"
  post "/student/upload_image" => "teacher#upload_image"
  get "/teachers/reviewed_quizzes" => "teacher#reviewed_quizzes"
  get "/teachers/video_reviewed_quizzes" => "teacher#video_reviewed_quizzes"
  get "/teachers/preview_reviewed_quiz" => "teacher#preview_reviewed_quiz"
  get "/teachers/preview_question" => "teacher#preview_question"
  get "/teachers/next_image" => "teacher#next_image"
  get "/home_page/remove_image" => "home_page#remove_image"

end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/home_page/_aform.html.erb
<table class="table table-condensed">
  <tr>
  <td><%= link_to "Add New Course", new_course_path, :class => 'btn btn-inverse btn-large' %></td>
  <td><%= link_to "Add New Degree", new_degree_path, :class => 'btn btn-inverse btn-large' %></td>
  <td><%= link_to "Add New Topic", new_topic_path, :class => 'btn btn-inverse btn-large' %></td>
    </tr>
  <tr>
    <td><%= link_to "Add New Test", new_test_path, :class => 'btn btn-inverse btn-large' %></td>
    <td><%= link_to "Add New Notes", new_book_path, :class => 'btn btn-inverse btn-large' %></td>
    <td><%= link_to "Add New Question", questions_path, :class => 'btn btn-inverse btn-large' %></td>
  </tr>
</table>

app/views/home_page/_courselist.html.erb
<%=label_tag :course %>
<% if @courses.nil? %>
<% else %>
    <select id="course" name="course" onchange="generate_test(this)" >
      <option>Select Course</option>

      <%@courses.each do |x| %>

          <option value="<%=x.id%>"><%=x.name%></option>
      <% end %>
    </select>

<%end %>

app/views/home_page/_d_list.html.erb
<ul class="tabs collapsed" style="display: none">
  <% if @flag == true %>
      <li value="" class="odd"><%= @degrees.last %></li>
  <% else %>

      <% @degrees.each_with_index do |degree,index| %>

          <a href="javascript:void(0)" id="degree_<%=index%>" onclick="selectDegreeList('degree_<%=index %>',<%=degree.id %>)" >
            <li value="<%=degree.id%>" class="<%=index % 2 == 0 ? 'even':'odd' %>"><%=degree.name%></li>
          </a>

      <% end %>

  <% end %>


</ul>

app/views/home_page/_get_details.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Student Detail</h4>
    </div>
    <div class="modal-body">

      <h4 class="modal-title">Student Info</h4>

      <table class="table table-condensed">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Certification</th>
          <th>Courses</th>
        </tr>
        <tr>
          <td><%= @student.name %></td>
          <td><%= @student.email %></td>
          <td><%= @certification.name if @certification %></td>
          <td>
            <% @packages.each_with_index do |package, index| %>
              <% if index == 0 %>
                <%= package.name %>
              <% else %>
                <br><%= package.name %>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>

      <h4 class="modal-title">Registered Courses</h4>

      <table class="table table-condensed">
        <tr>
          <th>Course</th>
          <th>Package</th>
          <th>Expires on</th>
          <th>Credit Left</th>
        </tr>
        <tbody>
          <% @packages.each do |package| %>
              <tr>
                <td><%= package.name %></td>
                <td><%= package.plan.capitalize %></td>
                <td><% if package.validity %>
                      <%= package.validity.day %> <%= I18n.t("date.abbr_month_names")[package.validity.month] %>, <%= package.validity.year %>
                  <% else %>
                      ∞
                  <% end %></td>
                <td><% if package.validity %>
                      PKR <%= package.credit_left %>/-
                  <% else %>
                      N/A
                  <% end %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div><!-- /.modal-content -->
</div>

app/views/home_page/_line.html.erb
 <style type="text/css">
      ${demo.css}
  </style>

  <script type="text/javascript">
      $(function () {
          $('#container').highcharts({
              title: {
                  text: 'Its my chart',
                  x: -200 //define the position of title
              },
              subtitle: {
                  text: 'Source: Umair Mahmood',
                  x: -200
              },
              xAxis: {
                  title: {
                      text: 'Months (Umair)'
                  },
                  categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec','Umr']
              },
              yAxis: {
                  title: {
                      text: 'Temperature (°C)'
                  },

                  plotLines: [{
                      value: 0,
                      width: 1,
                      color: '#808080'
                  }],
                  categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec','Umr']
              },
              tooltip: {
                  valueSuffix: '°C',
                  valuePrefix: 'A-'
              },
              legend: { // right box to represent the lines and their names
                  layout: 'horizontal', // can be horizontal
                  align: 'center',
                  verticalAlign: 'bottom',
                  borderWidth: 1
              },
              series: [{
                  name: 'Maldeeves',
                  color: 'blue', // give the color attribute
                  data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6,8.7]
              }, {
                  name: 'New York',
                  data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5,8.7]
              }, {
                  name: 'Berlin',
                  data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0,8.7]
              }, {
                  name: 'London',
                  data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8,8.7]
              }]
          });
      });
  </script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

app/views/home_page/_notes_courses.html.erb
<ul class="tabs collapsed">

  <% @notes_course_list.each_with_index do |course,index| %>

      <li onclick="getNotes(<%=course.id%>)" class="<%=index % 2 == 0 ? 'even':'odd' %>"><%=course.name%></li>

  <% end %>

</ul>

app/views/home_page/_register_user.html.erb
<h2>Please register yourself</h2>
<div class="row">
  <div class="span5">
    <%= form_for @user, :url => {:controller => 'home_page', :action => 'create_user_registration'} do |f| %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email,:required => true, autofocus: true ,:class=>'row_field' %>
        </div>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name,:required => true, :pattern => '^[a-zA-Z]+?[^\\\/:*?"<>|\n\r]+$' ,:class=>'row_field' %>
        </div>

        <div class="field">
          <%= f.label :phone %>
          <%= f.phone_field :phone ,:required => true,:class=>'row_field' %>
        </div>

        <div class="field">
          <%= f.label :password %>
          <% if @validatable %>
              <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
          <%= f.password_field :password, autocomplete: "off" ,:required => true,:class=>'row_field' %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, autocomplete: "off" ,:required => true,:class=>'row_field' %>

        </div>

        <input type="hidden" id="role" name="role" value="2" >
        <input type="hidden" id="b_id" name="b_id" value="<%=@board_id%>" >
        <input type="hidden" id="degree_id" name="degree_id" value="<%=@degree_id%>" >
        <input type="hidden" id="course_id" name="course_id" value="<%=@course_id%>" >
        <input type="hidden" id="mcq" name="mcq" value="<%=@mcq%>" >
        <input type="hidden" id="fill" name="fill" value="<%=@fill%>" >
        <input type="hidden" id="true_false" name="true_false" value="<%=@true_false%>" >
        <input type="hidden" id="descriptive" name="descriptive" value="<%=@descriptive%>" >




        <div class="actions">
          <%= f.submit "Register", :class => 'btn btn-large btn-inverse' %>
        </div>
    <% end %>
  </div>
</div>

app/views/home_page/_usform.html.erb
<%= link_to "sign out", sign_out_path,method: :delete %>

app/views/home_page/about_us.html.erb
<div class="abotus">
  <div class="aboutus_holder container">
    <h2>About Us</h2>
    <p>
      ELS aims to ease the problems faced by students and teachers through digital platforms.</p>
    <p> Founded in 2014, e-Learning Services (ELS) is developed and managed by a team of professional educators and entrepreneurs. The idea was conceived when, among many others, a physics teacher for O/A Level studies was fed-up by the traditional methods of assessing students. Exam development and then evaluation was a hideous task for him; when he wanted to devote more of his time to students. Thus, the idea to design a digital platform to cater this problem came across.</p>
    <p> Prolific meetings with technology experts further flourished the idea, and finally an initial website was created and launched in early 2015. The website was assessed and endorsed by many teachers, as it was a clear solution to their problem. Initially, the system was designed to accommodate the simple MCQ based questions. Later on, other testing techniques like fill in the blanks, true/false, descriptive/structured questions, etc. were also incorporated. Hence, making ELS a complete student assessment tool.</p>
    <p>The major edge ELS enjoys is the vast pool of questions it stores in its database – and that number is increasing day by day. Thus, students can always have new and more creative questions to solve. Usually a student is never presented a question which is already been attempted before by him, but even if it is repeated, it comes with different options. Teachers simply love this feature. At ELS, we are continuously striving to incorporate more and more creative methods for testing students.

    </p>
  </div>
</div>

app/views/home_page/how_it_works.html.erb
<div class="abotus">
  <div class="aboutus_holder container">
    <h2>How It works </h2>
    <p>
      ELS aims to ease the problems faced by students and teachers through digital platforms.</p>
    <p> Founded in 2014, e-Learning Services (ELS) is developed and managed by a team of professional educators and entrepreneurs. The idea was conceived when, among many others, a physics teacher for O/A Level studies was fed-up by the traditional methods of assessing students. Exam development and then evaluation was a hideous task for him; when he wanted to devote more of his time to students. Thus, the idea to design a digital platform to cater this problem came across.</p>
    <p> Prolific meetings with technology experts further flourished the idea, and finally an initial website was created and launched in early 2015. The website was assessed and endorsed by many teachers, as it was a clear solution to their problem. Initially, the system was designed to accommodate the simple MCQ based questions. Later on, other testing techniques like fill in the blanks, true/false, descriptive/structured questions, etc. were also incorporated. Hence, making ELS a complete student assessment tool.</p>
    <p>The major edge ELS enjoys is the vast pool of questions it stores in its database – and that number is increasing day by day. Thus, students can always have new and more creative questions to solve. Usually a student is never presented a question which is already been attempted before by him, but even if it is repeated, it comes with different options. Teachers simply love this feature. At ELS, we are continuously striving to incorporate more and more creative methods for testing students.

    </p>
  </div>
</div>

app/views/home_page/quiz.html.erb
<% if @register %>
<%= render 'register_user' %>
<% else %>

  <% $user_test_history = @user_test_history_id %>
    <%= render 'signed_in_quiz' %>
<% end%>

<div id="descriptive_modal" style="overflow:scroll;" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Descriptive Quiz</h4>
      </div>
      <div class="modal-body">
        <div class=" viual_right col">

          <h3>Your test will be evaluated in a short time. Thank you!</h3>

        </div>


      </div>

      <div class="modal-footer">
        <a href="/user/test_reviews" class="btn btn-default" >Close</a>
      </div>

    </div>
  </div>
</div>

<script type="text/javascript">

 </script>

app/views/home_page/try_it.html.erb
<% if current_user.is_active %>
  <%= render 'uform' %>
<% else %>
    <br>
    <div id="error" class="alert alert-danger" style="display: inline">
      <strong>Your payment is still pending.</strong>
    </div>
    <br><br><br><br><br><br>
<% end %>

<!--<div class="field">-->
  <!--<select id="course" name="course" required>-->
    <!--<option value="">Select Course</option>-->

    <!--<%# @courses.each do |course| %>-->
        <!--<%# if !@course.nil? && course.id == @course.id %>-->
            <!--<option selected value="<%#=course.id%>"><%#=course.name%></option>-->
        <!--<%# elsif params[:course_id].present? %>-->
            <!--<%# if course.id.to_s == params[:course_id] %>-->
                <!--<option value="<%#=course.id %>" selected><%#=course.name%></option>-->
            <!--<%# end %>-->
        <!--<%# else %>-->
            <!--<option value="<%#=course.id%>"><%#=course.name%></option>-->
        <!--<%# end %>-->
    <!--<%# end %>-->
  <!--</select>-->
<!--</div>-->
<!--<div id = "course_list">-->

<!--</div>-->