config/routes.rb
ExamsSystem::Application.routes.draw do
  resources :news_feeds

  mount Ckeditor::Engine => '/ckeditor'

  get "/topic_linkings/fetch_topic_linkings" => "topic_linkings#fetch_topic_linkings"

  resources :topic_linkings do
    collection do
      post :get_course_link
      get :get_topic_course_link
    end
  end

  resources :course_linkings
  resources :news_feeds
  resources :ckeditor, controller: 'ckeditor/'

  resources :membership_plans

  get "/questions/fetch_courses" => "questions#fetch_courses"
  get "/questions/fetch_details" => "questions#fetch_details"
  get "/questions/fetch_ques" => "questions#fetch_ques"
  get "/questions/fetch_course" => "questions#fetch_course"
  get "workflow_paths/fetch_reviews" => "workflow_paths#fetch_reviews"
  get "/topics/fetch_courses" => "topics#fetch_courses"
  get "/topics/fetch_table" => "topics#fetch_table"

  get "workflow_paths" => "workflow_paths#index"
  get "workflow_paths/toggle_workflow" => "workflow_paths#toggle_workflow"
  get "user" => "teacher#index"

  get 'auth/:provider/callback' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  get "user/new" => "teacher#new"
  post "user/save_result"
  get "user/my_profile"
  get "user/progress"
  put 'user/update_password'
  post "user/request_teacher"
  get "user/get_courses_by_degree_id"
  get "user/dashboard"
  get "user/ReTakeTest"
  get "user/manage_courses" => "user#manage_courses"
  get "/teachers/fetch_users" => "teacher#fetch_users"

  put "/user/update_courses" => "user#update_courses"

  delete "user.:id" => "teacher#destroy"

  get "home_page/user/my_profile" => "user#my_profile"
  get "home_page/checkout_form" => "home_page#checkout_form"
  get "/home_page/receipt" => "home_page#receipt"

  put "user/update"
  get "/courses/get_courses_by_degree_id"

  get "/boards/manage_boards" => "boards#manage_boards"
  get "/degrees/manage_degrees" => "degrees#manage_degrees"

  get "/course_linkings/manage_course_linkings" => "course_linkings#manage_course_linkings"
  get "/courses/manage_courses" => "courses#manage_courses"

  get "/courses/fetch_courses" => "courses#fetch_courses"
  get "/quizzes/fetch_courses" => "quizzes#fetch_courses"
  get "/quizzes/fetch_quizzes" => "quizzes#fetch_quizzes"

  get "/topics/fetch_topics" => 'topics#fetch_topics'

  resources :boards

  resources :topics do
    collection do
      get :get_courses
      get :get_topics
    end
  end

  resources :teacher do
    collection do
      get :get_courses
      get :teacher_courses
      post :course_register
      get :accept_student
      get :reject_student

    end

  end

  resources :books do
    collection do
      get :get_courses
    end
  end

  resources :services, except: [:show] do
    collection do
      post :sign_in
      get :get_all_boards
      get :get_all_degrees
      get :is_questions_exists
      get :fetch_questions
      get :get_lookup_data
      get :is_test_exists
      get :get_questions_by_test_code
      get :get_options_by_question_id
      get :verify_answers
      get :get_courses_by_teacher
      get :get_questions
      get :get_els_questions
      get :quiz
      post :create_quiz
      get :get_quiz_list
      get :get_student_quiz_list
      get :get_live_score_list
      get :live_score_details
      get :get_topics
      get :verify_answers_web
      get :show_quiz
      post :upload_image
      get :fetch_teacher_list
      get :fetch_quizzes
      get :fetch_answers
      post :save_remarks
      post :upload_video
      post :comment_feedback
      get :reviewed_quiz
      get :submit_feedback
      get :finish_review
      get :quizzes_list
      get :get_test_history_details
    end
  end

  resources :questions do
    collection do
      get :get_courses
      get :get_ques
      get :add_questions
      get :get_tests
      get :render_view
      get :render_view_edit
      get :delete_ques
      get :get_limit
      get :demo
      get :questions_approval
      get :approve_question
      get :next_question
      get :previous_question
      post :approve_by_teacher
      post :past_paper_history_param
      get :past_paper_history_param_edit
      post :reject_by_teacher
      get :reject_question
      post :reject_question
      get :add_comment_to_question
      get :get_questions_by_status
      get :get_question_details_for_approval
      get :questions_exits
      put :update_topic
      get :remove_option
      get :questions_detail
      get :get_question_detail
      get :enable_question_review
      get :get_course_linking
      get :get_topic_course_link
      get :get_all_topics_from_topic_linking
      get :rejected_questions
    end
  end

  get "home_page/index"
  get "home_page/get_courses" => 'home_page#get_courses'
  get "home_page/get_degrees" => 'home_page#get_degrees'
  get "home_page/get_tests" => 'home_page#get_tests'
  get "home_page/instructions" => 'home_page#instructions'
  post "home_page/instructions" => 'home_page#instructions'
  post "home_page/quiz" => 'home_page#quiz'
  get "home_page/quiz" => 'home_page#quiz'
  get "home_page/next_ques" => 'home_page#next'
  get "home_page/user_graph" => 'home_page#user_graph'
  get "home_page/get_notes_courses" => 'home_page#notes_courses'
  get "home_page/get_notes" => 'home_page#get_notes'
  get "home_page/create_user_registration" => "home_page#create_user_registration"
  post "home_page/sign_in_user" => "home_page#sign_in_user"
  get "home_page/add_user_test" =>  "home_page#add_user_test"
  get "home_page/is_user_signed_in" => "home_page#is_user_signed_in"
  get "home_page/demo" => "home_page#demo"
  get "admin_panel" => "home_page#admin_panel"
  get "home_page/save_data" => 'home_page#save_data'
  get "home_page/save_answer" => 'home_page#save_answer_to_session'
  get "home_page/get_answer" => 'home_page#get_answer_from_session'
  get "aboutUs" => 'home_page#about_us'
  get "pricing" => 'home_page#pricing'
  get "try_it" => 'home_page#try_it'
  post "home_page/get_topic" => 'home_page#get_topic'
  get "how_it_works" => 'home_page#how_it_works'
  get "testimonials" => 'home_page#testimonials'
  get "home_page/assign_member_ship_plan" => "home_page#assign_member_ship_plan"
  post "home_page/checkout" => "home_page#checkout"

  get "home_page/get_varients"
  get "home_page/get_backup"
  get "home_page/payments" => "home_page#payments"
  post "/homepage/set_access" => "home_page#set_access"
  get "/home_page/questions/questions_detail" => "questions#questions_detail"
  post "/home_page/get_details" => "home_page#get_details"
  get "/homepage/check_student_package" => "home_page#check_student_package"
  post "/homepage/check_package" => "home_page#check_package"
  get "/home_page/fetch_teachers" => "home_page#fetch_teachers"

  resources :tests do
    collection do
      get :get_courses
      get :get_questions
    end
  end
  resources :quizzes do
    collection do
      get :get_courses
      get :get_questions
      get :get_els_questions
      get :test_exists
      get :get_questions_by_course
      get :get_topics
      get :get_next_question
    end
  end

  get "/home_page/get_session", :to => 'home_page#get_session'

  resources :courses

  resources :degrees

  resources :roles

  root :to => "home_page#index"

  delete "/user/delete_package", to: "user#delete_package"

  get "/user/add_course", to: "user#add_course"

  get "/user/fetch_packages", to: "user#fetch_packages"

  get "/user/buy", to: "user#buy"

  get "/user/purchase", to: "user#purchase"

  devise_for :users, :controllers=> {:sessions=> "users/sessions",
                                   :confirmations => "users/confirmations",
                                   :passwords => "users/passwords",
                                   :unlocks => "users/unlocks",
                                   :registrations => "users/registrations",
                                   :omniauth_callbacks => "users/omniauth_callbacks"

  }

  devise_scope :user do
    get "sign_up" => "users/registrations#new"
    get "sign_in" => "users/sessions#new"
    delete "sign_out" => "users/sessions#destroy"
    put "users/save_form_2" => "users/registrations#save_form_2"
    get "/user_exists" => "users/registrations#user_exists"
    post "/save_form_1" => "users/registrations#save_form_1"
    post "/save_form_2" => "users/registrations#save_form_2"
    post "/save_form_3" => "users/registrations#save_form_3"
    post "/registration" => "users/registrations#registration"
    get "/registration" => "users/registrations#registration"
  end

  post '/tinymce_assets' => 'tinymce_assets#create'

  get "/student/fetch_image" => "teacher#fetch_image"
  post "/student/upload_video" => "teacher#upload_video"
  get "/student_test" => "teacher#student_test"

  post "/save_remarks" => "teacher#save_remarks"
  get "/user/test_reviews" => "user#test_reviews"
  get "/user/quiz_answers" => "user#quiz_answers"
  get "/student/show_answer" => "user#show_answer"

  get "new_students" => "teacher#new_students"
  get "manage_students" => "teacher#manage_students"
  get "/check_quiz" => "teacher#check_quiz"

  get "/student/review_question" => "teacher#review_question"
  post "/student/submit_feedback" => "user#submit_feedback"
  get "/comment_feedback" => "teacher#comment_feedback"
  get "/get_teachers" => "home_page#get_teachers"
  post "/teachers/finish_review" => "teacher#finish_review"
  post "/home_page/upload_image" => "home_page#upload_image"
  post "/student/upload_image" => "teacher#upload_image"
  get "/teachers/reviewed_quizzes" => "teacher#reviewed_quizzes"
  get "/teachers/video_reviewed_quizzes" => "teacher#video_reviewed_quizzes"
  get "/teachers/preview_reviewed_quiz" => "teacher#preview_reviewed_quiz"
  get "/teachers/preview_question" => "teacher#preview_question"
  get "/teachers/next_image" => "teacher#next_image"
  get "/home_page/remove_image" => "home_page#remove_image"

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    auth = request.env["omniauth.auth"]
    params = request.env["omniauth.params"]

    @user = User.from_omniauth(auth)

    if @user.persisted?
      if params["form"] == "login"
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        sign_in @user
        render :status => 200, :json => { :user => { :email => @user.email, :name => @user.name } }
      end
    else
      render :status => 401, :json => { :errors => alert }
      # session["devise.facebook_data"] = request.env["omniauth.auth"]
      # redirect_to new_user_registration_url
    end
  end


end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  layout "login_layout"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout "login_layout"
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create

    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    yield resource if block_given?
    if current_user.is_student?
      redirect_to user_my_profile_path
      return
    else
      redirect_to admin_panel_path
      return
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper

  def valid_packages(user_id)
    User.find_by_id(user_id).user_packages.where("validity > ?", Time.now)
  end

end

app/views/user/_fetch_packages.html.erb
<div class="field" id="fetch">
  <form action="/user/buy" data-remote="true" id="asd">
    <div>
      Please choose your package.
      you can see the package details below..
    </div>
    <div>
      <%= @course.name %><br>
      <input type="radio" name="plan" value="1">Free<br>
      <input type="radio" name="plan" value="2">Value<br>
      <input type="radio" name="plan" value="3">Complete<br>

      <br>
      <button type="submit" class="btn btn-primary">Buy</button>
    </div>

  </form>
</div>

<script>
  $('#asd').on('ajax:success', function(e, data, status, xhr){
    $('#purchase_container').html(data);
    $('#fetch').hide();
  })
</script>

app/views/user/_submit_feedback.html.erb
<div class="alert alert-success">
  <strong>Thank you for your feedback!</strong>
</div>

app/views/user/my_profile.html.erb
<div class="user_profile_holder" style="padding-top: 60px">
  <div class="container">
    <h1>User Profile Page</h1>
    <div class="user_profile_left ">
      <ul class="u_left_holder">
        <li><a class="avtar" href="javascript:void(0)">
          <% if @user.avatar.present?%>
              <%= image_tag @user.avatar.url , :class=>'avatar img-circle img-thumbnail' , :width => '200' , :height => '200' %>
          <% else %>
              <img src="/assets/FB-profile-avatar.jpg" class="avatar img-circle img-thumbnail"  width="200" height="200" alt=""></a></li>
          <% end %>
          <% if current_user.is_student? %>

              <li><a  href="/user/manage_courses">
                <i class="fa fa_icon fa-book"></i>
                Manage Courses</a> </li>

              <li><a  href="/user/test_reviews">
                <i class="fa fa_icon fa-book"></i>
                Test Reviews</a> </li>

              <li><a  href="#" id="test_code">
                <i class="fa fa_icon fa-book"></i>
                Attempt Test Code</a> </li>
              <!--<li><a  href="/user/manage_courses">-->
                <!--<i class="fa fa_icon fa-book"></i>-->
                <!--Manage Courses</a> </li>-->

          <% end %>

          </ul>
    </div>

    <div id="myModal" style="overflow:scroll;" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Attempt Test Code</h4>
          </div>
          <div class="modal-body">
            <div class=" viual_right col">

              <h2>Enter Code</h2>

              <fieldset>

                <div class="pre_header_row">
                  <div id="not_present" class='alert alert-error' style='color:red;display: none'>
                    <strong>Sorry!</strong> There is no test against this test code.
                  </div>

                  <div id="not_registered" class='alert alert-error' style='color:red;display: none'>
                    <strong>Sorry!</strong> You are not registered with this course.
                  </div>

                  <div id="credit_limit" class='alert alert-error' style='color:red;display: none'>
                    <strong>Sorry!</strong> Your package's credit has reached it's limit.
                  </div>

                  <div id="free_package" class='alert alert-error' style='color:red;display: none'>
                    <strong>Sorry!</strong> You can not attempt a descriptive test with a <strong>FREE PACKAGE</strong>.
                  </div>

                  <div id="package_expired" class='alert alert-error' style='color:red;display: none'>
                    <strong>Sorry!</strong> Your package has expired.
                  </div>

                  <div id="student_not_allowed" class='alert alert-error' style='color:red;display: none'>
                    <strong>Sorry!</strong> Your are not allowed to attempt this test.
                  </div>

                  <form method="post" action="/homepage/check_package" data-remote="true" id="attempt_test_code" >
                    <input type="text" name="test_code" class="text form-control" placeholder="Test Code">
                    <input type="hidden" name="test_flag" value="2" >
                    <button type="submit" class="btn btn-primary modal_btn">Submit</button>
                  </form>
                </div>

              </fieldset>

            </div>


          </div>
        </div>
      </div>
    </div>
    <div class="user_profile_right ">

      <ul class="user_profile_nav">
        <li>
          <a href="javascript:void(0)">Profile

          </a>
        </li>
      </ul>
      <ul class="u_right_holder">
        <li class="form-group">
          <h3>Email</h3>
          <span><%= @user.email%></span>
        </li>
        <li>
          <h3>Name</h3>
          <span><%= best_in_place @user, :name, :url => user_update_path, :as => :input %><i class="fa fa-pencil-square-o"></i></span>
        </li>
        <li>
          <h3>Phone Number</h3>
          <span><%= best_in_place @user, :phone, :url => user_update_path, :as => :input %><i class="fa fa-pencil-square-o"></i></span>
        </li>
        <li>
          <h3>Last Test Attempted On</h3>
          <span><%=@last_user_history.updated_at.to_date unless @last_user_history.nil?%></span>
          <%=link_to "Re-Take", "/"%>
        </li>
        <%= form_for @user, :url => user_update_path, :html => { :multipart => true } do |f| %>
            <li>
              <h3>Picture</h3>
              <%= f.file_field :avatar %>
              <%= f.submit "Update Picture", :class=>'btn btn-primary'%>

            </li>
        <% end %>
        <%= form_for(@user, :url => { :action => "update_password" } ) do |f| %>
            <li>
              <h3><%= f.label :password %> </h3>
              <%= f.password_field :password, autocomplete: "off" %><i>(leave blank if you don't want to change it)</i>
            </li>

            <li>
              <h3><%= f.label :password_confirmation %></h3>
              <%= f.password_field :password_confirmation, autocomplete: "off" %>
            </li>

            <li>
              <h3><%= f.label :current_password %> </h3>
              <%= f.password_field :current_password, autocomplete: "off" %><i>(we need your current password to confirm your changes)</i>
              <%= params[:notice] unless params[:notice].nil? %>
            </li>
            <li>
              <h3></h3>
              <%= f.submit "Change Password", :class=>'btn btn-primary' %>
            </li>
        <% end %>
      </ul>



      <!--############### teachers followed #############-->
      <ul class="user_profile_nav">
        <li>
          <a href="javascript:void(0)">Teachers Panel
                  <span class="menu_active">
                    <i class="fa fa-caret-up"></i>
                </span>
          </a>
        </li>
      </ul>
      <ul class="u_right_holder">
        <%@user.teacher_requests.each do |request| %>

            <li>
              <div class="row">
                <div class="col-md-4">
                  <strong><font color="black"><%= User.where(teacher_token: request.teacher_token).first.name %></font></strong>
                </div>
                <div class="col-md-4">
                  <strong><font color="black"><%=request.teacher_token %></font></strong>
                </div>
                <div class="col-md-4">
                  <span><%=request.status %></span>
                </div>
              </div>
            </li>

        <% end %>

        <%= form_for :teacher_request,url: '/user/request_teacher',remote: true,id: 'request_teacher_form' do |f| %>
            <li>
              <h3><%= f.label :teacher_token %> </h3>
              <%= f.text_field :teacher_token %>
            </li>
            <%=f.hidden_field :student_id,value: @user.id %>
            <%=f.hidden_field :student_email,value: @user.email %>
            <%=f.hidden_field :student_name,value: @user.name %>
            <%=f.hidden_field :status,value: "PENDING" %>
            <li>
              <h3></h3>
              <%= f.submit "Request", :class=>'btn btn-inverse' %>
            </li>
        <% end %>
      </ul>


    </div>
  </div>
</div>
<script type="text/javascript">

//    $(document).ready(function() {
//        /* Activating Best In Place */
//        jQuery(".best_in_place").best_in_place();
//    });


    $('#attempt_test_code').on('ajax:complete', function(e, data){
        if (data.responseJSON.success){
            window.location.replace(data.responseJSON.url);
        }
    });

    $('#attempt_test_code').on('ajax:error', function(e, data, status, xhr){
        if (data.responseJSON.flag == "not_present")
        {
            $('#not_present').show();
            $("#not_present").delay(2500).fadeOut();
        }
        else if (data.responseJSON.flag == "not_registered")
        {
            $('#not_registered').show();
            $("#not_registered").delay(2500).fadeOut();
        }
        else if (data.responseJSON.flag == "credit_limit")
        {
            $('#credit_limit').show();
            $("#credit_limit").delay(2500).fadeOut();
        }
        else if (data.responseJSON.flag == "free_package")
        {
          $('#free_package').show();
          $("#free_package").delay(2500).fadeOut();
        }
        else if (data.responseJSON.flag == "package_expired")
        {
          $('#package_expired').show();
          $("#package_expired").delay(2500).fadeOut();
        }
        else if (data.responseJSON.flag == "student_not_allowed")
        {
            $('#student_not_allowed').show();
            $("#student_not_allowed").delay(2500).fadeOut();
        }

    })

    $('#test_code').on('click', function(){
        $('#myModal').modal('toggle');
    });
    //    function update_image() {
    //
    //        $.post($("form.edit_user").attr("action"), $("form.edit_user").serialize(), function (response) {
    //
    //            if (response.success) {
    //                alert("Image Updated successfully");
    //            }
    //            else {
    //                return false;
    //            }
    //
    //        }, "json")
    //    }
</script>

app/views/user/show_answer.html.erb
<div class="page-content-wrapper">
  <div class=" stat_holder" style="margin-top: 20px">
    <label><strong>Question Statement</strong></label>
    <%= raw @question.statement %>
  </div>

  <% if @question.question_type == 1 %>
      <div class="question_p_section">
        <ul>
          <% if @student_choice and @student_choice != "ref_3"  %>
              <li class='option_question'>
                <%= @options.where(id: @student_choice.to_i).first.statement %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <% if @options.where(id: @student_choice.to_i).first.is_answer == 1 %>
                  <span class="label label-success">Right</span>
                <% else %>
                    <span class="label label-danger">Wrong</span>
                <% end %>
              </li>
          <% else %>
              <li class='option_question'>
                No attempted
              </li>
          <% end %>
        </ul>
      </div>

  <% elsif @question.question_type == 4 %>

      <ul>
          <% if @student_choice and @student_choice != "ref_3" %>
            <li class='option_question'>
              <%= @student_choice + "  " %>
              <% if @student_choice == @options.first.statement %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <span class="label label-success">Right</span>
              <% else %>
                  <span class="label label-danger">Wrong</span>
              <% end %>
            </li>
          <% else %>
            <li class='option_question'>
              No attempted
            </li>
          <% end %>
      </ul>

  <% elsif @question.question_type == 3 %>

      <ul>
        <% if @student_choice and @student_choice != "ref_3" %>
          <li>
            <strong>Your answer: </strong><%= @student_choice %>
            <% if @options.first.statement.split('/').include?(@student_choice) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <span class="label label-success">Right</span>
            <% else %>
                <span class="label label-danger">Wrong</span>
            <% end %>
          </li>
        <% else %>
            <li>
              No attempted
            </li>
        <% end %>

      </ul>

  <% elsif @question.question_type == 2 %>
      <div class="field stat_holder">

        <% unless @answer.answer_detail %>
            <label><strong>Teacher Review</strong></label><br>
            <%  if @answer.answer_images.present? %>
                <%  @answer.answer_images.each do |image| %>
                    <%= image_tag image.image.url %><br><br>
                <% end %>
            <% end %>
        <% else %>
            <label><strong>Submitted Answer</strong></label>
            <%= raw @answer.answer_detail %>
        <% end %>
      </div>

      <div class="field stat_holder">
        <label><strong>Remarks</strong></label>
        <%= @answer.remarks %>
      </div>

      <div class="field stat_holder">
        <label><strong>Marks</strong></label>
        <%= @answer.marks %> / <%= @question.marks %>
      </div>

      <% if @answer.video_file_name %>
          <div class="field stat_holder">
            <label><strong>Video Review</strong></label>
            <div  style="width:800px; margin:0 auto;">
              <video id="example_video_1" class="video-js vjs-default-skin vjs-big-play-centered"
                     controls preload="auto" width="640" height="400"
                     poster="http://video-js.zencoder.com/oceans-clip.png"
                     data-setup='{"example_option":true}'>
                <source src="<%= @answer.video %>" type="video/webm" />
                <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
              </video>
            </div>

          </div>
      <% end %>
  <% end %>


  <% if @finish_flag %>

      <% if !@test.student_feedback %>
          <div id="feedback">
            <%= form_tag "/student/submit_feedback", remote: true, id: "submit_feedback" do |f| %>
                <div class="field stat_holder">
                  <label><strong>Please Provide your feedback on ELS review</strong></label>
                  <%= text_field_tag :student_feedback, nil, size: 140 %><br>
                  <%= submit_tag "Submit Feedback", class: "btn btn-primary" %>
                </div>
            <% end %>
          </div>
      <% end %>



    <%= link_to "Finish Review", user_test_reviews_path, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Next Answer", student_show_answer_path, class: "btn btn-primary" %>
  <% end %>

</div>

<script type="text/javascript">
  $('#submit_feedback').on('ajax:success', function(e, data, status, xhr){
    $('#feedback').html(data);
  })
</script>